fullname: Multivariate polynomials
shortname: multinomials
organization: math-comp
opam_name: coq-mathcomp-multinomials
community: false
action: true
coqdoc: false

synopsis: >-
  A Multivariate polynomial Library for the Mathematical Components Library
description: |-
  This library provides a library for monomial algebra,for
  multivariate polynomials over ring structures and an extended theory
  for polynomials whose coefficients range over commutative rings and
  integral domains.

publications:
- pub_url: http://www.strub.nu/biblio/pdf/conf-cpp-BernardBRS16.pdf
  pub_title: "Formal proofs of transcendence for e and pi as an application of multivariate and symmetric polynomials."
  pub_doi: 10.1145/2854065.2854072

authors:
- name: Pierre-Yves Strub
  initial: true

opam-file-maintainer: Cyril Cohen <cyril.cohen@inria.fr>

opam-file-version: dev

license:
  fullname: CeCILL-B
  identifier: CECILL-B
  file: LICENSE

supported_coq_versions:
  text: Coq 8.10 to 8.12
  opam: '{ (>= "8.10" & < "8.13~") | (= "dev") }'

tested_coq_opam_versions:
- version: '1.12.0-coq-8.10'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.11'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.12'
  repo: 'mathcomp/mathcomp'
- version: 'coq-8.10'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.11'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.12'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-dev'
  repo: 'mathcomp/mathcomp-dev'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{ (>= "1.12.0" & < "1.13~") | (= "dev")  }'
  description: |-
    [MathComp ssreflect 1.12](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-algebra
    version: '{ (>= "1.12.0" & < "1.13~") | (= "dev")  }'
  description: |-
    [MathComp algebra 1.12](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-field
    version: '{ (>= "1.12.0" & < "1.13~") | (= "dev")  }'
  description: |-
    [MathComp field 1.12](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-finmap
    version: '{ (>= "1.5" & < "1.6~") | (= "dev")  }'
  description: |-
    [MathComp finmap 1.5.1](https://github.com/math-comp/finmap)
- opam:
    name: coq-mathcomp-bigenough
    version: '{>= "1.0.0"}'
  description: |-
    [MathComp bigenough 1.0.0 or later](https://github.com/math-comp/bigenough)

namespace: SsrMultinomials

keywords:
- name: multivariate polynomials
- name: monoid algebra

category:
- name: "Math/Algebra/Multivariate polynomials"
- name: "Math/Algebra/Monoid algebra"

documentation: |-
  ## Acknowledgments
  ### Contributors
  - [Florent Hivert](https://www.lri.fr/~hivert/)
  - [Laurent
  Thery](https://www-sop.inria.fr/marelle/personnel/Laurent.Thery/moi.html)

  ### This library is also the result of discussions with
  - Sophie Bernard
  - [Cyril Cohen](http://www.cyrilcohen.fr/)
  - [Laurence Rideau](http://www-sop.inria.fr/members/Laurence.Rideau/)
